ipam:
  # Build this locally with the docker file
  # located in this repository
  image: phpipam
  ports:
    - 9101:80
  environment:
    - IPAM_USER=ipam
    - IPAM_PASS=ipampw01
    - IPAM_NAME=ipam
    - IPAM_HOST=mysql
  links:
    - mysql
mysql:
  image: mysql:5.7
  volumes:
    - /var/opt/ipam:/var/lib/mysql
  environment:
    - MYSQL_USER=ipam
    - MYSQL_PASSWORD=ipampw01
    - MYSQL_DATABASE=ipam
    - MYSQL_ROOT_PASSWORD=password

