ipam:
  # Build this locally with the docker file
  # located in this repository
  image: phpipam
  # Run on first start to setup the mysql db, this is hacky i'll come up with something nice later
  # entrypoint: java -Dconfig.file=/opt/collins/conf/production.conf -Dhttp.port=9000 -Dlogger.file=/opt/collins/conf/logger.xml -cp /opt/collins/lib/* collins.DbUtil /opt/collins/conf/evolutions/
  ports:
    - 9101:80
  environment:
    - IPAM_USER=ipam
    - IPAM_PASS=ipampw01
    - IPAM_NAME=ipam
    - IPAM_HOST=mysql
  links:
    - mysql
mysql:
  image: mysql:5.7
  volumes:
    - /var/opt/ipam:/var/lib/mysql
  environment:
    - MYSQL_USER=ipam
    - MYSQL_PASSWORD=ipampw01
    - MYSQL_DATABASE=ipam
    - MYSQL_ROOT_PASSWORD=password

